# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

# ignore all warnings from all pods
inhibit_all_warnings!

target 'use-bdd' do

pod 'AFNetworking'

end

target 'use-bddTests' do

pod 'AFNetworking'
pod 'Kiwi'

end

